#!/bin/bash -x

CODE_MRHOT=/scratch/shuiyao/sci/rhot/rhot_mhist
CODE_METAL=/scratch/shuiyao/sci/metals/metals
DATA_FOLDER=/proj/shuiyao
MODEL=$1
OUT_FOLDER=/scratch/shuiyao/sci/PHEW_TEST/$MODEL/

SNAPNUM=108
SNAPSTR=108
echo $CODE_MRHOT $DATA_FOLDER/$MODEL/snapshot z0 $SNAPNUM
$CODE_MRHOT $DATA_FOLDER/$MODEL/snapshot z0 $SNAPNUM
echo $CODE_METAL $DATA_FOLDER/$MODEL/snapshot z0 $SNAPNUM
$CODE_METAL $DATA_FOLDER/$MODEL/snapshot z0 $SNAPNUM
mv mrhot_z0_$SNAPSTR $OUT_FOLDER
mv tabmet_z0_$SNAPSTR $OUT_FOLDER

SNAPNUM=78
SNAPSTR=078
echo $CODE_MRHOT $DATA_FOLDER/$MODEL/snapshot z1 $SNAPNUM
$CODE_MRHOT $DATA_FOLDER/$MODEL/snapshot z1 $SNAPNUM
echo $CODE_METAL $DATA_FOLDER/$MODEL/snapshot z1 $SNAPNUM
$CODE_METAL $DATA_FOLDER/$MODEL/snapshot z1 $SNAPNUM
mv mrhot_z1_$SNAPSTR $OUT_FOLDER
mv tabmet_z1_$SNAPSTR $OUT_FOLDER
